// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::prelude::*;
use serde_derive::{Deserialize, Serialize};

#[derive(
    Queryable, Identifiable, Selectable, Clone, Debug, PartialEq, Default, Serialize, Deserialize,
)]
#[diesel(primary_key(did))]
#[diesel(table_name = crate::schema::indexer::did_record)]
#[diesel(check_for_backend(diesel::pg::Pg))]
#[serde(rename_all = "camelCase")]
pub struct DidRecord {
    pub did: String,
    #[diesel(column_name = "ckbAddress")]
    pub ckb_address: String,
    pub handle: String,
    #[diesel(column_name = "signingKey")]
    pub signing_key: String,
    #[diesel(column_name = "txHash")]
    pub tx_hash: String,
    #[diesel(column_name = "outIndex")]
    pub out_index: i32,
    pub document: String,
    pub height: i64,
    #[diesel(column_name = "createdAt")]
    pub created_at: String,
    pub valid: bool,
}
